services:
  - type: web
    name: kindle-book-translator
    runtime: docker
    region: frankfurt
    plan: free
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: LOG_API_KEY
        sync: false
